application: hlutimetable
version: 1
runtime: python27
api_version: 1
threadsafe: false
handlers:
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /.*
  script: main.py
