application: hlutimetable
version: 1
runtime: python27
api_version: 1
threadsafe: false
handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: endpoint_api.APPLICATION
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /img
  static_dir: static/img
- url: /.*
  script: main.py
libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0